CREATE TABLE active_carriers (
  DotNumber int PRIMARY KEY NOT NULL,
  LegalName varchar(150) NOT NULL,
  DBAName varchar(150) NOT NULL,
  CarrierOperation varchar(150) NOT NULL,
  HMFlag varchar(150) NOT NULL,
  PCFlag varchar(150) NOT NULL,
  PHYStreet varchar(150) NOT NULL,
  PHYCity varchar(150) NOT NULL,
  PHYState varchar(150) NOT NULL,
  PHYZip int NOT NULL,
  PHYCountry varchar(150) NOT NULL,
  MailingStreet varchar(150) NOT NULL,
  MailingCity varchar(150) NOT NULL,
  MailingState varchar(150) NOT NULL,
  MailingZip int NOT NULL,
  MailingCountry varchar(150) NOT NULL,
  Telephone varchar(150) NOT NULL,
  Fax varchar(150) NOT NULL,
  EmailAddress varchar(150) NOT NULL,
  MCS150Date varchar(150) NOT NULL,
  MCS150Mileage int NOT NULL,
  MCS150MileageYear int NOT NULL,
  AddDate varchar(150) NOT NULL,
  OICState varchar(150) NOT NULL,
  NBRPowerUnit int NOT NULL,
  DriverTotal int NOT NULL
)